src/main/java/com/prgrms/himin/shop/api/ShopController.java, src/main/java/com/prgrms/himin/shop/application/ShopService.java, src/main/java/com/prgrms/himin/shop/domain/Category.java, src/main/java/com/prgrms/himin/shop/domain/Shop.java, src/main/java/com/prgrms/himin/shop/domain/ShopStatus.java, src/main/java/com/prgrms/himin/shop/dto/request/ShopCreateRequest.java, src/main/java/com/prgrms/himin/shop/dto/response/ShopResponse.java
가게 생성 기능을 구현하였습니다.
- Entity와 DTO에서 모두 유효성 검증을 하고 있습니다.
- 다른 사항들은 기본적인 것들이라 크게 설명할 부분은 없는 것 같습니다.
Issue Number: HIMIN-79
=> [HIMIN-79] feat: 가게 생성 기능 구현

src/main/java/com/prgrms/himin/shop/api/ShopController.java, src/main/java/com/prgrms/himin/shop/application/ShopService.java
가게 단건 조회 기능을 구현하였습니다.
Issue Number: HIMIN-81
간단한 로직이라 컨트롤러와 서비스에서만 코드를 작성하였는데, 혹시나 제가 놓친 부분 있는지 확인 부탁드립니다!
=> [HIMIN-81] feat: 가게 단건 조회 기능 구현

src/main/java/com/prgrms/himin/menu/api/MenuController.java, src/main/java/com/prgrms/himin/menu/application/MenuService.java, src/main/java/com/prgrms/himin/menu/domain/Menu.java, src/main/java/com/prgrms/himin/menu/domain/MenuStatus.java, src/main/java/com/prgrms/himin/menu/dto/request/MenuCreateRequest.java, src/main/java/com/prgrms/himin/menu/dto/response/MenuCreateResponse.java
- MenuController에서 MenuCreateRequest DTO데이터를 입력받아 데이터베이스에 저장합니다.
- Menu와 연관된 도메인 MenuOptionGroup, MenuOption와 관련 데이터를 입력 받지 않고 Menu도메인과 관련된 데이터만 저장 합니다.
- MenuOptionGroup, MenuOption 도메인 관련 데이터는 다른 컨트롤러에서 입력 받아 저장 되고 연관 관계 매핑으로 Menu 도메인과 연결 할 예정입니다.
Issue Number: HIMIN-88
=> [HIMIN-88] feat : 메뉴 생성 기능 구현

src/main/java/com/prgrms/himin/menu/domain/MenuOption.java
=> [No-JIRA] hotfix : price 컬럼 오기로 인한 버그 수정

src/main/java/com/prgrms/himin/shop/api/ShopController.java, src/main/java/com/prgrms/himin/shop/application/ShopService.java, src/main/java/com/prgrms/himin/shop/domain/Shop.java, src/main/java/com/prgrms/himin/shop/dto/request/ShopUpdateRequest.java, src/main/java/com/prgrms/himin/shop/dto/response/ShopResponse.java
- 찜 수, 가게 상태를 제외한 나머지 가게 정보들에 대해서 수정하는 기능을 구현하였습니다.
- 해당 로직을 구현하면서 고민한 부분에 대해서는 [TRW](https://www.notion.so/backend-devcourse/TRW-The-Reason-Why-aafbac387fd6415386ec324e63e8e5d5?p=c8071865ab174e19b361d2e1ec40a3b6&pm=s) 페이지에 정리해두었습니다.
- 가게 상태를 수정하는 기능을 구현하였습니다.
- `UpdateRequest`가 가게 정보들을 담는 DTO, 가게 상태를 담는 DTO 총 두 개가 필요합니다. 어떻게 두 개의 DTO를 관리할까 고민하다가 각각 static inner 클래스로 작성하는 방식으로 처리하였습니다.
Issue Number: HIMIN-83  
찜 기능은 다음 스프린트 때 구현하는 것으로 합의되어 구현하지 않았습니다.
=> [HIMIN-83] feat: 가게 정보 수정 기능 구현

src/main/java/com/prgrms/himin/member/api/MemberController.java, src/main/java/com/prgrms/himin/member/application/MemberService.java, src/main/java/com/prgrms/himin/member/domain/MemberRepository.java, src/main/java/com/prgrms/himin/member/dto/request/MemberLoginRequest.java
- loginId, password를 body로 받아 컨트롤러에 보내줍니다.
- 이때 loginId, password로 무분별하게 긴 문자를 보내는 것을 방지하기 위해 Size validation을 합니다.
- `tryToLoginWith()` 메소드로 id와 password가 일치하는 member가 있는지 조회여부를 boolean(isPresent)으로 반환합니다.
- 컨트롤러는 그에 맞게 HttpStatus만을 반환합니다. (따로 ResponseBody 존재 x)
Issue Number: HIMIN-87
=> [HIMIN-87] feat: 로그인 기능 구현

src/main/java/com/prgrms/himin/shop/api/ShopController.java, src/main/java/com/prgrms/himin/shop/application/ShopService.java
가게 삭제 기능을 구현하였습니다.
Issue Number: HIMIN-86
=> [HIMIN-86] feat: 가게 삭제 기능 구현

src/main/java/com/prgrms/himin/menu/api/MenuController.java, src/main/java/com/prgrms/himin/menu/application/MenuService.java, src/main/java/com/prgrms/himin/menu/domain/MenuOptionGroup.java, src/main/java/com/prgrms/himin/menu/domain/MenuOptionGroupRepository.java, src/main/java/com/prgrms/himin/menu/dto/request/MenuOptionGroupCreateRequest.java, src/main/java/com/prgrms/himin/menu/dto/response/MenuOptionGroupCreateResponse.java
- MenuController에서 MenuOptionGroup DTO데이터와 메뉴 id를 pk로 입력받아 데이터베이스에 저장합니다.
Issue Number: HIMIN-91
=> [HIMIN-91] feat : 메뉴 옵션 그룹 생성 기능 구현

src/main/java/com/prgrms/himin/member/api/MemberController.java, src/main/java/com/prgrms/himin/member/application/MemberService.java, src/main/java/com/prgrms/himin/member/domain/Address.java, src/main/java/com/prgrms/himin/member/domain/Member.java
단순 delete 구현하였습니다.
다만 구현 중 cascade=CascadeType.ALL과 orphanremoval에 대한 자세한 이해가 선행되지 않아,
추후 Address 추가기능 구현 후 다시 delete에 대해 어느정도 테스트해 보고 회원탈퇴에 대한 기능수정이 이루어질 수도 있습니다.
Issue Number: HIMIN-85
=> [HIMIN-85] feat : 회원 삭제 기능 구현

src/main/java/com/prgrms/himin/menu/api/MenuController.java, src/main/java/com/prgrms/himin/menu/application/MenuService.java, src/main/java/com/prgrms/himin/menu/domain/MenuOption.java, src/main/java/com/prgrms/himin/menu/domain/MenuOptionRepository.java, src/main/java/com/prgrms/himin/menu/dto/request/MenuOptionCreateRequest.java, src/main/java/com/prgrms/himin/menu/dto/response/MenuOptionCreateResponse.java
- MenuController에서 MenuOption DTO, 메뉴 id, 메뉴 옵션 그룹 id를 입력으로 받는다.
- 메뉴 id는 올바른 옵션 그룹 id가 입력되었는지 검증하는데 사용된다.
- 메뉴 옵션 그룹의 id는 메뉴 옵션의 pk로 데이터베이스에 저장합니다.
Issue Number: HIMIN-95
=> [HIMIN-95] feat : MenuOption 저장 기능 구현

src/main/java/com/prgrms/himin/member/api/MemberController.java, src/main/java/com/prgrms/himin/member/application/MemberService.java
회원의 모든 주소 조회 기능 구현
Issue Number: HIMIN-101
=> [HIMIN-101] feat : 회원 주소 조회 구현

src/main/java/com/prgrms/himin/menu/domain/Menu.java, src/main/java/com/prgrms/himin/menu/domain/MenuOption.java, src/main/java/com/prgrms/himin/menu/domain/MenuOptionGroup.java
메뉴, 메뉴 옵션 그룹, 메뉴 옵션 연관 관계 매핑 기능 및 편의 메소드 추가
Issue Number: HIMIN-107
=> [HIMIN-107] feat : 메뉴, 메뉴 옵션 그룹, 메뉴 옵션 연관 관계 매핑 기능 및 편의 메소드 추가

src/main/java/com/prgrms/himin/member/api/MemberController.java, src/main/java/com/prgrms/himin/member/application/MemberService.java, src/main/java/com/prgrms/himin/member/domain/Member.java
회원id와 주소id를 pathvariable로 받아 해당 주소를 삭제하는 기능을 구현했습니다.
Issue Number: HIMIN-103
=> [HIMIN-103] feat : 주소 삭제 구현

src/main/java/com/prgrms/himin/menu/api/MenuController.java, src/main/java/com/prgrms/himin/menu/application/MenuService.java, src/main/java/com/prgrms/himin/menu/dto/response/MenuCreateResponse.java, src/main/java/com/prgrms/himin/menu/dto/response/MenuOptionGroupResponse.java, src/main/java/com/prgrms/himin/menu/dto/response/MenuOptionResponse.java, src/main/java/com/prgrms/himin/menu/dto/response/MenuResponse.java
메뉴 id를 입력 받으면 메뉴 옵션 그룹, 메뉴 옵션을 리스트로 반환 하도록 기능을 추가 하였습니다!
Issue Number: HIMIN-89
=> [HIMIN-89] feat : 메뉴 단건 조회 기능 추가

src/main/java/com/prgrms/himin/menu/domain/MenuOption.java, src/main/java/com/prgrms/himin/menu/domain/MenuOptionGroup.java
- DB에 저장 되기전 엔티티의 id는 null이다.
- 이 때 엔티티의 동등성 비교를 위해 id의equals를 호출하면 NPE가 발생한다.
- 초기에 null인 id의 equals대신 Object 클래스의 equals를 활용하여 문제를 해결 하였다. 
=> [NO-JIRA] hotfix : 메뉴, 메뉴옵션, 메뉴옵션그룹 생성 안되는 버그 수정

src/main/java/com/prgrms/himin/menu/api/MenuController.java, src/main/java/com/prgrms/himin/menu/application/MenuService.java, src/main/java/com/prgrms/himin/menu/domain/Menu.java, src/main/java/com/prgrms/himin/shop/domain/Shop.java
- 메뉴 관련 path를 가게 하위에 두도록 수정
- 그에 따른 서비스도 수정
- 가게, 메뉴 연관 관계 매핑 추가
- 연관 관계 편의 메서드 추가
Issue Number: HIMIN-116
- 메뉴의 경로를 수정하여 경로를 의존하는 경우 영향을 받을 수 있다.
=> [HIMIN-116] refactor : 컨트롤러에서 메뉴와 관련 경로를 가게 하위 경로로 수정

src/main/java/com/prgrms/himin/menu/dto/response/MenuCreateResponse.java, src/main/java/com/prgrms/himin/menu/dto/response/MenuOptionCreateResponse.java, src/main/java/com/prgrms/himin/menu/dto/response/MenuOptionGroupCreateResponse.java, src/main/java/com/prgrms/himin/menu/dto/response/MenuOptionGroupResponse.java, src/main/java/com/prgrms/himin/menu/dto/response/MenuOptionResponse.java, src/main/java/com/prgrms/himin/menu/dto/response/MenuResponse.java
메뉴 관련 반환 dto에서 id를 포함 하도록 수정
Issue Number: HIMIN-117
=> [HIMIN-117] refactor : 메뉴 관련 반환 dto에서 id를 포함하여 반환 하도록 수정

src/main/java/com/prgrms/himin/menu/api/MenuController.java, src/main/java/com/prgrms/himin/menu/application/MenuService.java, src/main/java/com/prgrms/himin/menu/domain/Menu.java, src/main/java/com/prgrms/himin/menu/dto/request/MenuUpdateRequest.java
메뉴, 메뉴 상태 수정 기능 추가
Issue Number: HIMIN-90
=> [HIMIN-90] feat : 메뉴, 메뉴 상태 수정 기능 추가

src/main/java/com/prgrms/himin/global/common/EnumValidator.java, src/main/java/com/prgrms/himin/global/common/ValidEnum.java
- DTO의 다른 필드들은 `MethodArgumentNotValidException` 예외를 터뜨려 일관적으로 예외 처리가 가능하지만, 맞지 않은 Enum이 들어올 경우에는 `HttpMessageNotReadableException: JSON parse error` 예외가 터져서 다른 검증들과 함께 예외 처리 하기 힘들었다.
- Enum Validator를 적용하면, `MethodArgumentNotValidException`을 터뜨리기 때문에 위의 문제를 해결할 수 있다.
Issue Number: HIMIN-114
DTO에 적용하는 것은 리팩토링 기간에 하기로 결정했습니다.
추후 DTO 적용 시 필요사항
- DTO에서 Enum을 String으로 받도록 변경해야한다.
- toEntity로 변경할 때 String의 Enum값을 Enum으로 변경하는 작업이 필요하다.
=> [HIMIN-114] feat: Enum Validator 구현

src/main/java/com/prgrms/himin/menu/api/MenuController.java, src/main/java/com/prgrms/himin/menu/application/MenuService.java, src/main/java/com/prgrms/himin/menu/domain/MenuOptionGroup.java, src/main/java/com/prgrms/himin/menu/dto/request/MenuOptionGroupUpdateRequest.java
메뉴 옵션 그룹 이름 수정 기능 추가
Issue Number: HIMIN-93
=> [HIMIN-93] feat : 메뉴 옵션 그룹 이름 수정 기능 추가

src/main/java/com/prgrms/himin/menu/api/MenuController.java, src/main/java/com/prgrms/himin/menu/application/MenuService.java, src/main/java/com/prgrms/himin/menu/domain/MenuOption.java, src/main/java/com/prgrms/himin/menu/dto/request/MenuOptionUpdateRequest.java
메뉴 옵션 수정 기능 추가
Issue Number: HIMIN-118
=> [HIMIN-118] feat : 메뉴 옵션 수정 기능 추가

src/main/java/com/prgrms/himin/menu/api/MenuController.java, src/main/java/com/prgrms/himin/menu/application/MenuService.java
메뉴 옵션 삭제 기능 구현
Issue Number: HIMIN-97
=> [HIMIN-97] feat : 메뉴 옵션 삭제 기능 구현

src/main/java/com/prgrms/himin/menu/domain/Menu.java
=> [NO-JIRA] !hotfix : Merge conflict 해결시 누락된 Menu 메소드 추가

src/main/java/com/prgrms/himin/order/api/OrderController.java, src/main/java/com/prgrms/himin/order/application/OrderService.java
=> [HIMIN-74] feat : 주문 단건조회 구현

src/main/java/com/prgrms/himin/menu/api/MenuController.java, src/main/java/com/prgrms/himin/menu/application/MenuService.java
###메뉴 삭제 기능 구현
- 메뉴 삭제 기능 구현
- 메뉴를 삭제하면 하위에 있는 메뉴 옵션 그룹, 메뉴 옵션 또한 삭제 된다. 
=> [HIMIN-92] feat : 메뉴 삭제 기능 구현

src/main/java/com/prgrms/himin/menu/api/MenuController.java, src/main/java/com/prgrms/himin/menu/application/MenuService.java
메뉴 옵션 그룹 삭제 기능 추가
Issue Number: HIMIN-94
=> [HIMIN-94] feat : 메뉴 옵션 그룹 삭제 기능 추가

src/main/java/com/prgrms/himin/shop/api/ShopController.java
http 상태 코드 CRUD 별로 동일하게 수정 
Issue Number: HIMIN-120
=> [HIMIN-120] refactor : http 상태 코드 CRUD 별로 동일하게 수정

src/main/java/com/prgrms/himin/shop/application/ShopService.java, src/main/java/com/prgrms/himin/shop/dto/request/ShopCreateRequest.java, src/main/java/com/prgrms/himin/shop/dto/request/ShopUpdateRequest.java
- 가게 `RequestDto`에 Enum Validator를 적용하였습니다.
Issue Number: HIMIN-121
=> [HIMIN-121] refactor: 가게 RequestDto Enum Validator 적용

src/main/java/com/prgrms/himin/menu/application/MenuService.java
트랜잭션 어노테이션 readonly 옵션 통일
Issue Number: HIMIN-123
=> [HIMIN-123] refactor : 트랜잭션 어노테이션 readonly 옵션 통일

src/main/java/com/prgrms/himin/member/domain/Grade.java, src/main/java/com/prgrms/himin/menu/domain/Menu.java, src/main/java/com/prgrms/himin/menu/domain/MenuStatus.java, src/main/java/com/prgrms/himin/order/domain/OrderStatus.java, src/main/java/com/prgrms/himin/shop/domain/Category.java, src/main/java/com/prgrms/himin/shop/domain/Shop.java, src/main/java/com/prgrms/himin/shop/domain/ShopStatus.java
Enum 상수 대문자로 변경, 상수마다 개행 추가.
Issue Number: HIMIN-122
=> [HIMIN-122] beommo enum refactoring

src/main/java/com/prgrms/himin/member/api/MemberController.java, src/main/java/com/prgrms/himin/member/application/MemberService.java, src/main/java/com/prgrms/himin/member/domain/Address.java, src/main/java/com/prgrms/himin/menu/api/MenuController.java, src/main/java/com/prgrms/himin/menu/application/MenuService.java, src/main/java/com/prgrms/himin/menu/domain/Menu.java, src/main/java/com/prgrms/himin/menu/domain/MenuOption.java, src/main/java/com/prgrms/himin/menu/domain/MenuOptionGroup.java, src/main/java/com/prgrms/himin/shop/api/ShopController.java, src/main/java/com/prgrms/himin/shop/application/ShopService.java, src/main/java/com/prgrms/himin/shop/domain/Shop.java
=> [HIMIN-124]  beommo refactoring enter

src/main/java/com/prgrms/himin/menu/application/MenuService.java, src/main/java/com/prgrms/himin/menu/domain/MenuValidator.java, src/main/java/com/prgrms/himin/menu/dto/request/MenuOptionGroupCreateRequest.java, src/main/java/com/prgrms/himin/order/application/OrderService.java
- 메뉴 서비스 수정
- 오더 서비스 수정 
Issue Number: HIMIN-128
=> [HIMIN-128] refactor : 메뉴 검증 로직 리팩터링

src/main/java/com/prgrms/himin/global/error/exception/ErrorCode.java
- ErrorCode 추가
Issue Number: HIMIN-125
=> [HIMIN-125] feat: ErrorCode 추가

src/main/java/com/prgrms/himin/global/error/exception/ErrorCode.java, src/main/java/com/prgrms/himin/member/application/MemberService.java, src/main/java/com/prgrms/himin/member/domain/Address.java, src/main/java/com/prgrms/himin/member/domain/Member.java, src/main/java/com/prgrms/himin/menu/application/MenuService.java, src/main/java/com/prgrms/himin/menu/domain/Menu.java, src/main/java/com/prgrms/himin/menu/domain/MenuOption.java, src/main/java/com/prgrms/himin/menu/domain/MenuOptionGroup.java, src/main/java/com/prgrms/himin/menu/domain/MenuValidator.java, src/main/java/com/prgrms/himin/shop/application/ShopService.java, src/main/java/com/prgrms/himin/shop/domain/Shop.java
에러 코드 추가에 따른 유효성 검증 예외 수정
Issue Number: HIMIN-129
=> [HIMIN-129] refactor : 에러 코드 추가에 따른 유효성 검증 예외 수정

src/main/java/com/prgrms/himin/member/application/MemberService.java, src/main/java/com/prgrms/himin/shop/application/ShopService.java
- collect(Collectors.toList()) → toList() 로 변경
Issue Number: HIMIN-130
=> [HIMIN-130] refactor: collect(Collectors.toList()) → toList() 로 변경

src/main/java/com/prgrms/himin/global/error/exception/ErrorCode.java, src/main/java/com/prgrms/himin/order/application/OrderService.java, src/main/java/com/prgrms/himin/order/domain/Order.java, src/main/java/com/prgrms/himin/order/domain/OrderHistory.java, src/main/java/com/prgrms/himin/order/domain/OrderItem.java, src/main/java/com/prgrms/himin/order/domain/SelectedOption.java
에러코드 추가에 따른 유효성 검증 수정
Issue Number: HIMIN-129
=> [HIMIN-129] refactor : 에러코드 추가에 따른 유효성 검증 수정

src/main/java/com/prgrms/himin/shop/domain/Shop.java
=> [HIMIN-129] style : 에러코드 오타 수정

build.gradle
=> [NO-JIRA] !hotfix : build.gradle 수정

src/main/java/com/prgrms/himin/menu/api/MenuController.java, src/main/java/com/prgrms/himin/menu/application/MenuService.java
refactor : api 명세 수정으로 인한 경로 수정
Issue Number: HIMIN-132
- 프로젝트 내에 코드 중에 메뉴 컨트롤러를 의존하는 코드는 없기 때문에 영향이 없다.
- 포스트맨 등으로 호출 하는 경우 영향이 있다.
=> [HIMIN-132] refactor : api 명세 수정으로 인한 경로 수정

src/test/java/com/prgrms/himin/setup/domain/ShopSetUp.java, src/test/java/com/prgrms/himin/setup/request/ShopCreateRequestBuilder.java
Shop 관련 테스트 시 필요한 test fixture 구현하였습니다. 
- domain
- request
Issue Number: HIMIN-131
=> [HIMIN-131] test: 가게 test fixture 추가 (domain, request)

src/main/java/com/prgrms/himin/global/error/GlobalExceptionHandler.java
GlobalExceptionHandler에 BusinessException 핸들링 추가
=> [NO-JIRA] !hotfix : BusinessExceptoin 핸들링 추가

src/test/java/com/prgrms/himin/member/api/MemberControllerTest.java, src/test/java/com/prgrms/himin/setup/domain/MemberSetUp.java, src/test/java/com/prgrms/himin/setup/request/MemberLoginRequestBuilder.java
MemberController 로그인 테스트 구현
Issue Number: HIMIN-133
=> [HIMIN-133] MemberController 로그인 테스트 구현

src/main/java/com/prgrms/himin/menu/dto/request/MenuUpdateRequest.java, src/test/java/com/prgrms/himin/menu/api/MenuControllerTest.java, src/test/java/com/prgrms/himin/setup/domain/MenuSetUp.java, src/test/java/com/prgrms/himin/setup/request/MenuCreateRequestBuilder.java, src/test/java/com/prgrms/himin/setup/request/MenuUpdateRequestBuilder.java
- 메뉴 컨트롤러 테스트 구현
- 메뉴 컨트롤러를 위한 fixture 구현
Issue Number: HIMIN-146
=> [HIMIN-146] test : 메뉴 컨트롤러 테스트 구현

src/test/java/com/prgrms/himin/member/api/MemberControllerTest.java, src/test/java/com/prgrms/himin/setup/domain/MemberSetUp.java
MemberController member 조회 테스트 구현
Issue Number: HIMIN-133
=> [HIMIN-133] MemberController member 조회 테스트 구현

src/test/java/com/prgrms/himin/menu/api/MenuOptionGroupControllerTest.java, src/test/java/com/prgrms/himin/setup/domain/MenuOptionGroupSetUp.java, src/test/java/com/prgrms/himin/setup/request/MenuOptionGroupRequestBuilder.java
메뉴 옵션 그룹 생성 테스트 구현
Issue Number: HIMIN-148
=> [HIMIN-148] test : 메뉴 옵션 그룹 생성 테스트 구현

src/main/java/com/prgrms/himin/global/error/exception/ErrorCode.java, src/main/java/com/prgrms/himin/member/api/MemberController.java, src/main/java/com/prgrms/himin/member/application/MemberService.java, src/main/java/com/prgrms/himin/member/domain/Member.java, src/main/java/com/prgrms/himin/member/dto/request/MemberCreateRequest.java, src/main/java/com/prgrms/himin/member/dto/request/MemberUpdateRequest.java
회원 업데이트 기능 구현
Issue Number: HIMIN-147
회원 생성시 잘못된 생일(오늘 이후를 생일로 지정) 기입시 에러를 터뜨린다.
=> [HIMIN-147] 회원 업데이트 기능 구현

src/main/java/com/prgrms/himin/menu/dto/request/MenuOptionGroupUpdateRequest.java, src/test/java/com/prgrms/himin/menu/api/MenuOptionGroupControllerTest.java, src/test/java/com/prgrms/himin/setup/domain/MenuOptionGroupSetUp.java, src/test/java/com/prgrms/himin/setup/request/MenuOptionGroupUpdateRequestBuilder.java
메뉴 옵션 그룹 수정 테스트 구현
Issue Number: HIMIN-148
=> [HIMIN-148] test : 메뉴 옵션 그룹 수정 테스트 구현

src/test/java/com/prgrms/himin/member/api/MemberControllerTest.java, src/test/java/com/prgrms/himin/setup/request/MemberUpdateRequestBuilder.java
회원 업데이트 테스트 구현
Issue Number: HIMIN-133
=> [HIMIN-133] 회원 업데이트 테스트 구현

src/test/java/com/prgrms/himin/member/api/MemberControllerTest.java
회원 삭제 테스트 구현
Issue Number: HIMIN-133
=> [HIMIN-133] test : 회원 삭제 테스트 구현

src/test/java/com/prgrms/himin/menu/api/MenuOptionGroupControllerTest.java
메뉴 옵션 그룹 삭제 테스트 구현
Issue Number: HIMIN-148
=> [HIMIN-148] test : 메뉴 옵션 그룹 삭제 테스트 구현

src/test/java/com/prgrms/himin/menu/api/MenuControllerTest.java, src/test/java/com/prgrms/himin/menu/api/MenuOptionControllerTest.java, src/test/java/com/prgrms/himin/setup/domain/MenuOptionSetUp.java, src/test/java/com/prgrms/himin/setup/request/MenuOptionCreateRequestBuilder.java
메뉴 옵션 생성 테스트 구현
Issue Number: HIMIN-150
=> [HIMIN-150] test : 메뉴 옵션 생성 테스트 구현

src/test/java/com/prgrms/himin/shop/api/ShopControllerTest.java
- 테스트 후 롤백이 되지 않아 DB에 여러 데이터가 쌓였습니다.
- 전체 조회 테스트 경우 해당 테스트 메서드에서 생성한 데이터 뿐만 아니라 그 전에 실행된 테스트에서 만들어진 데이터들도 함꼐 조회되어 테스트가 통과하지 못했습니다.
- `@Transactiona` 어노테이션을 붙여 테스트 실행 후 롤백하도록 하였습니다.
Issue Number: HIMIN-149
=> [HIMIN-149] fix: 가게 컨트롤러 테스트 전체 조회 버그 수정

src/test/java/com/prgrms/himin/menu/api/MenuOptionControllerTest.java, src/test/java/com/prgrms/himin/setup/request/MenuOptionUpdateRequestBuilder.java
메뉴 옵션 수정 테스트 기능 구현
Issue Number: HIMIN-150
=> [HIMIN-150] test : 메뉴 옵션 수정 테스트 기능 구현

src/main/java/com/prgrms/himin/member/api/MemberController.java, src/main/java/com/prgrms/himin/member/application/MemberService.java, src/main/java/com/prgrms/himin/member/domain/Address.java, src/main/java/com/prgrms/himin/member/dto/request/AddressUpdateRequest.java
address update 구현
Issue Number: HIMIN-151
=> [HIMIN-151] address update 구현

src/test/java/com/prgrms/himin/menu/api/MenuOptionControllerTest.java, src/test/java/com/prgrms/himin/setup/domain/MenuOptionSetUp.java
메뉴 옵션 삭제 테스트 기능 추가
Issue Number: HIMIN-150
=> [HIMIN-150] test : 메뉴 옵션 삭제 테스트 기능 추가

src/main/java/com/prgrms/himin/global/util/PhonePolicy.java, src/main/java/com/prgrms/himin/member/domain/Member.java, src/main/java/com/prgrms/himin/member/dto/request/MemberCreateRequest.java, src/main/java/com/prgrms/himin/shop/domain/Shop.java
Issue Number: HIMIN-152
MemberCreateRequest에서도 Regex를 이용한 전화번호 검증
=> [HIMIN-152] feat : PhonePolicy 구현

src/test/java/com/prgrms/himin/order/api/OrderControllerTest.java, src/test/java/com/prgrms/himin/setup/domain/OrderItemSetUp.java, src/test/java/com/prgrms/himin/setup/request/OrderCreateRequestBuilder.java, src/test/java/com/prgrms/himin/setup/request/SelectedMenuOptionRequestBuilder.java, src/test/java/com/prgrms/himin/setup/request/SelectedMenuRequestBuilder.java
Order생성 컨트롤러 테스트 구현
Issue Number: HIMIN-153
=> [HIMIN-153] Order생성 컨트롤러 테스트 구현

src/test/java/com/prgrms/himin/order/api/OrderControllerTest.java, src/test/java/com/prgrms/himin/setup/domain/OrderItemSetUp.java, src/test/java/com/prgrms/himin/setup/domain/OrderSetUp.java, src/test/java/com/prgrms/himin/setup/domain/SelectedOptionSetUp.java
Order조회 컨트롤러 테스트 구현
Issue Number: HIMIN-154
=> [HIMIN-154] Order조회 컨트롤러 테스트 구현

.github/workflows/CI.yml
CI용 yml 작성
Issue Number: HIMIN-135
=> [HIMIN-135] chore : CI용 yml 작성

src/main/java/com/prgrms/himin/member/domain/Address.java, src/main/java/com/prgrms/himin/menu/domain/Menu.java, src/main/java/com/prgrms/himin/menu/domain/MenuOption.java, src/main/java/com/prgrms/himin/menu/domain/MenuOptionGroup.java, src/main/java/com/prgrms/himin/order/domain/OrderItem.java, src/main/java/com/prgrms/himin/order/domain/SelectedOption.java
- equals() and hashCode() 삭제
Issue Number: HIMIN-137
=> [HIMIN-137] refactor: equals() and hashCode() 삭제

src/main/java/com/prgrms/himin/order/application/OrderService.java, src/main/java/com/prgrms/himin/order/domain/Order.java, src/test/java/com/prgrms/himin/order/api/OrderControllerTest.java, src/test/java/com/prgrms/himin/setup/domain/OrderSetUp.java
기능추가 X
Issue Number: HIMIN-136
주문금액 계산에서 가게의 배달팁까지 더해줌에 따라 Order의 price결과가 달라진다.
=> [HIMIN-136] refactor : 주문금액 계산로직에 가게 배달팁 추가

src/main/java/com/prgrms/himin/HiminApplication.java, src/main/java/com/prgrms/himin/delivery/api/DeliveryController.java, src/main/java/com/prgrms/himin/delivery/application/DeliveryService.java, src/main/java/com/prgrms/himin/delivery/domain/Delivery.java, src/main/java/com/prgrms/himin/delivery/domain/DeliveryHistory.java, src/main/java/com/prgrms/himin/delivery/domain/DeliveryHistoryRepository.java, src/main/java/com/prgrms/himin/delivery/domain/DeliveryRepository.java, src/main/java/com/prgrms/himin/delivery/domain/DeliveryStatus.java, src/main/java/com/prgrms/himin/delivery/dto/response/DeliveryResponse.java, src/main/java/com/prgrms/himin/global/common/BaseEntity.java, src/main/java/com/prgrms/himin/order/api/OrderController.java, src/main/java/com/prgrms/himin/order/domain/OrderStatus.java
Delivery 생성 구현
Issue Number: HIMIN-166
=> [HIMIN-166] Delivery 생성 구현

src/main/java/com/prgrms/himin/delivery/api/DeliveryController.java, src/main/java/com/prgrms/himin/delivery/api/RiderController.java, src/main/java/com/prgrms/himin/delivery/application/DeliveryService.java, src/main/java/com/prgrms/himin/delivery/application/RiderService.java, src/main/java/com/prgrms/himin/delivery/domain/Delivery.java, src/main/java/com/prgrms/himin/delivery/domain/DeliveryHistory.java, src/main/java/com/prgrms/himin/delivery/domain/DeliveryStatus.java, src/main/java/com/prgrms/himin/delivery/domain/Rider.java, src/main/java/com/prgrms/himin/delivery/domain/RiderRepository.java, src/main/java/com/prgrms/himin/delivery/dto/request/RiderCreateRequest.java, src/main/java/com/prgrms/himin/delivery/dto/response/DeliveryHistoryResponse.java, src/main/java/com/prgrms/himin/delivery/dto/response/DeliveryResponse.java, src/main/java/com/prgrms/himin/delivery/dto/response/RiderResponse.java, src/main/java/com/prgrms/himin/global/error/exception/ErrorCode.java, src/main/java/com/prgrms/himin/order/domain/OrderStatus.java
배차 기능에 따라 배달을 맡을 배달기사 클래스(Rider)구현.
Delivery - Rider는 다대 일 단방향 연관관계를 맺어주었습니다.
Issue Number: HIMIN-173
=> [HIMIN-173] 배차 기능 구현

src/main/java/com/prgrms/himin/delivery/api/DeliveryController.java, src/main/java/com/prgrms/himin/delivery/application/DeliveryService.java
배달 시작 구현
Issue Number: HIMIN-174
=> [HIMIN-174] feat : 배달 시작 구현

src/main/java/com/prgrms/himin/delivery/api/DeliveryController.java, src/main/java/com/prgrms/himin/delivery/application/DeliveryService.java
배달 완료 구현
Issue Number: HIMIN-175
=> [HIMIN-175] feat : 배달 완료 구현

src/main/java/com/prgrms/himin/delivery/application/DeliveryService.java, src/main/java/com/prgrms/himin/delivery/domain/DeliveryHistory.java, src/main/java/com/prgrms/himin/order/application/OrderService.java, src/main/java/com/prgrms/himin/order/domain/OrderHistory.java, src/main/java/com/prgrms/himin/order/dto/response/OrderResponse.java, src/main/java/com/prgrms/himin/order/event/DeliveryFinishedEvent.java, src/main/java/com/prgrms/himin/order/event/OrderEventHandler.java
참고
https://www.notion.so/backend-devcourse/52d6e8a2974840a986b969fae5d4d761?pvs=4
배달이 완료되면 DeliveryHistory를 저장한 이후, DeliveryFinshedEvent를 DeliveryService에서 발행하여(생성자로 생성한 이후 publish메소드 호출) OrderEventHandler에서 orderService의 finishOrder를 호출하도록 했습니다. (내부적으로 OrderHistory를 생성하여 저장합니다.)
-> 이로써 Delivery도메인은 Order도메인을 알 필요가 없습니다.(의존성이 필요가 없습니다.)
Issue Number: HIMIN-167
=> [HIMIN-167] Spring Event를 이용하여 배달 완료 구현

src/main/java/com/prgrms/himin/shop/api/ShopController.java, src/main/java/com/prgrms/himin/shop/application/ShopService.java, src/main/java/com/prgrms/himin/shop/dao/ShopRepositoryImpl.java, src/main/java/com/prgrms/himin/shop/domain/ShopRepositoryCustom.java, src/main/java/com/prgrms/himin/shop/dto/request/ShopSearchCondition.java, src/test/java/com/prgrms/himin/shop/api/ShopControllerTest.java
-- 가게와 메뉴를 조인하여 메뉴 이름 검색 기능 추가
-- 더 자세한 내용(조인이 실행될 경우 런타임에 어떤 쿼리가 실행되는지 등)은 아래 노션페이지에 기록하였습니다.
https://www.notion.so/backend-devcourse/OneToMany-DSL-f54be40650d34e3293cb228cf8d547f7?pvs=4 
Issue Number: HIMIN-161
=> [HIMIN-161] feat : 가게와 메뉴를 조인하여 메뉴이름을 포함한 가게를 검색할 수 있도록 수정

src/main/java/com/prgrms/himin/delivery/api/DeliveryController.java, src/main/java/com/prgrms/himin/delivery/application/DeliveryService.java, src/main/java/com/prgrms/himin/delivery/domain/DeliveryHistoryRepository.java, src/main/java/com/prgrms/himin/delivery/dto/response/DeliveryHistoryResponse.java
하나의 배달 Id에 대한 배달히스토리 조회 구현
참고 : https://www.notion.so/backend-devcourse/DeliveryHistoryResponse-940e0539d930435389ad5c596f22bd4f?pvs=4
Issue Number: HIMIN-177
=> [HIMIN-177] feat : 배달히스토리 조회 구현

src/main/java/com/prgrms/himin/global/error/exception/ErrorCode.java, src/main/java/com/prgrms/himin/order/application/OrderService.java, src/main/java/com/prgrms/himin/order/domain/OrderHistory.java, src/main/java/com/prgrms/himin/order/event/CookingFinishedEvent.java, src/main/java/com/prgrms/himin/order/event/OrderEventHandler.java, src/main/java/com/prgrms/himin/order/event/StartedCookingEvent.java, src/main/java/com/prgrms/himin/shop/api/ShopController.java, src/main/java/com/prgrms/himin/shop/application/ShopService.java
가게-주문간 조리 시작, 조리완료 이벤트처리 구현
Issue Number: HIMIN-179
=> [HIMIN-179] 가게-주문간 조리 시작, 조리완료 이벤트처리 구현

src/main/java/com/prgrms/himin/order/application/OrderService.java
=> [NO-JIRA] !hotfix : OrderService 닫는중괄호 추가

build.gradle, src/main/java/com/prgrms/himin/HiminApplication.java, src/main/java/com/prgrms/himin/global/config/security/JwtConfig.java, src/main/java/com/prgrms/himin/global/config/security/WebSecurityConfig.java, src/main/java/com/prgrms/himin/global/config/security/jwt/Jwt.java, src/main/java/com/prgrms/himin/global/config/security/jwt/JwtAuthentication.java, src/main/java/com/prgrms/himin/global/config/security/jwt/JwtAuthenticationFilter.java, src/main/java/com/prgrms/himin/global/config/security/jwt/JwtAuthenticationProvider.java, src/main/java/com/prgrms/himin/global/config/security/jwt/JwtAuthenticationToken.java, src/main/java/com/prgrms/himin/member/api/MemberController.java, src/main/java/com/prgrms/himin/member/application/MemberService.java, src/main/java/com/prgrms/himin/member/domain/Member.java, src/main/java/com/prgrms/himin/member/domain/MemberRepository.java, src/main/java/com/prgrms/himin/member/dto/request/MemberCreateRequest.java, src/main/java/com/prgrms/himin/member/dto/response/MemberLoginResponse.java, src/test/java/com/prgrms/himin/member/api/MemberControllerTest.java, src/test/java/com/prgrms/himin/setup/domain/MemberSetUp.java
- JWT 관련 설정, 토큰, 필터 구현
Issue Number: HIMIN-163
=> [HIMIN-163] JWT 관련 설정, 토큰, 필터 구현

src/main/java/com/prgrms/himin/member/domain/Address.java, src/main/java/com/prgrms/himin/member/domain/Member.java, src/main/java/com/prgrms/himin/member/dto/request/AddressCreateRequest.java, src/main/java/com/prgrms/himin/member/dto/request/AddressUpdateRequest.java, src/main/java/com/prgrms/himin/member/dto/request/MemberCreateRequest.java, src/main/java/com/prgrms/himin/member/dto/request/MemberLoginRequest.java, src/main/java/com/prgrms/himin/member/dto/request/MemberUpdateRequest.java, src/main/java/com/prgrms/himin/menu/domain/Menu.java, src/main/java/com/prgrms/himin/menu/domain/MenuOption.java, src/main/java/com/prgrms/himin/menu/domain/MenuOptionGroup.java, src/main/java/com/prgrms/himin/menu/dto/request/MenuCreateRequest.java, src/main/java/com/prgrms/himin/menu/dto/request/MenuOptionCreateRequest.java, src/main/java/com/prgrms/himin/menu/dto/request/MenuOptionGroupCreateRequest.java, src/main/java/com/prgrms/himin/menu/dto/request/MenuOptionGroupUpdateRequest.java, src/main/java/com/prgrms/himin/menu/dto/request/MenuOptionUpdateRequest.java, src/main/java/com/prgrms/himin/menu/dto/request/MenuUpdateRequest.java, src/main/java/com/prgrms/himin/order/domain/Order.java, src/main/java/com/prgrms/himin/order/domain/OrderItem.java, src/main/java/com/prgrms/himin/order/dto/request/OrderCreateRequest.java, src/main/java/com/prgrms/himin/order/dto/request/SelectedMenuRequest.java, src/main/java/com/prgrms/himin/shop/domain/Shop.java, src/main/java/com/prgrms/himin/shop/dto/request/ShopCreateRequest.java, src/main/java/com/prgrms/himin/shop/dto/request/ShopUpdateRequest.java
기존에 하드코딩으로 dto validation값들을 설정해 주었던 걸
엔티티단의 상수로 대체. 그에 따라 validation메시지도 수정.
Issue Number: HIMIN-188
=> [HIMIN-188] Dto validation refactor

src/main/java/com/prgrms/himin/member/domain/Member.java, src/main/java/com/prgrms/himin/member/domain/Permission.java
- Member 역할을 나타내는 Permission 이넘 클래스를 추가하였습니다.
현재 JWT 토근에 MemberId가 아닌 Member LoginId가 저장되고 있는데, 이 부분은 현재 할당한 일을 다 한 후에 수정하겠습니다!
=> [NO-ZIRA] fix: login with jwt

.gitignore, build.gradle, src/main/resources/application-local-create.yml, src/main/resources/application-local.yml, src/main/resources/application-prod.yml, src/main/resources/application-test.yml, src/main/resources/application.yml, src/test/java/com/prgrms/himin/order/api/OrderControllerTest.java, src/test/resources/application.yml
Issue Number: HIMIN-191
- 기존 mysql로 사용하였던 테스트를 h2 인메모리 데이터 베이스에서 하도록 변경하였습니다. 
- MODE를 mysql로 변경하여 직접적인 영향은 없습니다.
- 기존 로컬에서 mysql에 의존에서 h2 데이터베이스에서 개발하도록 변경 됩니다.
=> [HIMIN-191] feat, refactor : 공용으로 사용할 yml 파일 생성 및 H2 사용하여 테스트 하도록 변경

src/main/java/com/prgrms/himin/shop/domain/Shop.java, src/test/java/com/prgrms/himin/shop/application/ShopServiceTest.java
- [xx] 곤모슬 팀에서 정한 코딩 컨벤션과 일치하는가?
가게 생성 성공테스트 작성
Issue Number: HIMIN-194
=> [HIMIN-194] test : 가게 생성 성공테스트 작성

src/test/java/com/prgrms/himin/shop/application/ShopServiceTest.java
가게 조회 테스트코드 작성
Issue Number: HIMIN-197
=> [HIMIN-197] test : 가게 조회 테스트코드 작성

src/test/java/com/prgrms/himin/shop/application/ShopServiceTest.java
가게 업데이트 테스트 작성
Issue Number: HIMIN-200
=> [HIMIN-200] test : 가게 업데이트 테스트 작성

src/test/java/com/prgrms/himin/menu/application/MenuServiceTest.java
- 메뉴 조회 테스트 추가
Issue Number: HIMIN-202
=> [HIMIN-202] test: 메뉴 조회 테스트 추가

src/test/java/com/prgrms/himin/menu/application/MenuServiceTest.java, src/test/java/com/prgrms/himin/setup/request/MenuUpdateRequestBuilder.java
- 메뉴 상태 변경 테스트 추가
Issue Number: HIMIN-204
=> [HIMIN-204] test: 메뉴 상태 변경 테스트 추가

src/test/java/com/prgrms/himin/menu/application/MenuServiceTest.java, src/test/java/com/prgrms/himin/setup/request/MenuUpdateRequestBuilder.java
- 메뉴 삭제 테스트 추가
Issue Number: HIMIN-206
=> [HIMIN-206] test: 메뉴 삭제 테스트 추가

src/test/java/com/prgrms/himin/shop/application/ShopServiceTest.java
가게 삭제 테스트 구현
Issue Number: HIMIN-201
=> [HIMIN-201] test : 가게 삭제 테스트 구현

src/test/java/com/prgrms/himin/menu/application/MenuServiceTest.java
- 메뉴 서비스 테스트 CI 통과 안되는 문제 해결 (서비스 중복 제거)
=> [NO-ZIRA] fix: 메뉴 서비스 버그 수정

src/test/java/com/prgrms/himin/shop/application/ShopServiceTest.java
가게 다건조회 테스트 작성
Issue Number: HIMIN-207
=> [HIMIN-207] test : 가게 다건조회 테스트 작성

.github/workflows/CICD.yml, appspec.yml, scripts/deploy.sh
=> CD yml configure

src/test/java/com/prgrms/himin/order/application/OrderServiceTest.java, src/test/java/com/prgrms/himin/setup/factory/OrderDomainTestDependencyFactory.java, src/test/java/com/prgrms/himin/setup/factory/SelectedMenuFactory.java, src/test/java/com/prgrms/himin/setup/request/MenuCreateRequestBuilder.java, src/test/java/com/prgrms/himin/setup/request/MenuOptionCreateRequestBuilder.java, src/test/java/com/prgrms/himin/setup/request/MenuOptionGroupRequestBuilder.java, src/test/java/com/prgrms/himin/setup/request/SelectedMenuOptionRequestBuilder.java
- 기존에 있는 메뉴 관련 fixture에 데이터 추가
- 주문 서비스 테스트가 의존하는 클래스가 많아 팩터리 클래스를 만들어 분담하도록 기능 추가
- 주문 생성 테스트 기능 추가
Issue Number: HIMIN-195
=> [HIMIN-195] feat : 주문 서비스에서 주문 생성 기능 추가

src/test/java/com/prgrms/himin/member/application/MemberServiceTest.java
MemberServiceTest SpringBootTest로 변경
Issue Number: HIMIN-218
=> [HIMIN-218] refactor : MemberServiceTest SpringBootTest로 변경

src/test/java/com/prgrms/himin/menu/application/MenuOptionGroupServiceTest.java
- 메뉴 옵션 그룹 테스트 추가
Issue Number: HIMIN-205
=>  [HIMIN-205] test: 메뉴 옵션 그룹 테스트 추가

src/test/java/com/prgrms/himin/menu/application/MenuOptionServiceTest.java
- 메뉴 옵션 테스트 추가
Issue Number: HIMIN-221
=> [HIMIN-221] test: 메뉴 옵션 테스트 추가

src/test/java/com/prgrms/himin/member/application/MemberServiceTest.java
회원 로그인 테스트구현
Issue Number: HIMIN-219
=> [HIMIN-219] test : 회원 로그인 테스트구현

src/main/java/com/prgrms/himin/shop/application/ShopService.java, src/main/java/com/prgrms/himin/shop/domain/ShopRepository.java, src/main/java/com/prgrms/himin/shop/dto/response/ShopResponse.java
Issue Number: HIMIN-216
기존의 nextCursor구하는 로직의 오류를 바로잡았습니다.
=> [HIMIN-216] shop 리팩터링

src/main/resources/application-local-create.yml, src/main/resources/application-local.yml, src/main/resources/application-prod.yml, src/main/resources/application-test.yml
기본 배치 사이즈 설정 추가
Issue Number: HIMIN-226
배치 사이즈 설정으로 인해 기존 하나의 메서드에서 다수개의 쿼리가 발생한 경우 1000개 이하일 때 in절로 하나의 쿼리가 발생한다.
=> [HIMIN-226] feat : N + 1 문제를 해결하기 위해 기본 배치 사이즈 설정

src/test/java/com/prgrms/himin/delivery/application/DeliveryServiceTest.java, src/test/java/com/prgrms/himin/member/api/MemberControllerTest.java, src/test/java/com/prgrms/himin/member/application/MemberServiceTest.java, src/test/java/com/prgrms/himin/menu/api/MenuControllerTest.java, src/test/java/com/prgrms/himin/menu/api/MenuOptionControllerTest.java, src/test/java/com/prgrms/himin/menu/api/MenuOptionGroupControllerTest.java, src/test/java/com/prgrms/himin/menu/application/MenuOptionGroupServiceTest.java, src/test/java/com/prgrms/himin/menu/application/MenuOptionServiceTest.java, src/test/java/com/prgrms/himin/order/api/OrderControllerTest.java, src/test/java/com/prgrms/himin/shop/api/ShopControllerTest.java, src/test/resources/truncate.sql
Mock제외한 전 테스트 @Transactional -> @Sql로 수정
Issue Number: HIMIN-192
=> [HIMIN-192] Mock제외한 전 테스트 @Transactional -> @Sql로 수정

README.md
readme파일 수정
Issue Number: HIMIN-228
=> [HIMIN-228] docs: readme 파일 수정

src/test/java/com/prgrms/himin/menu/api/MenuControllerTest.java, src/test/java/com/prgrms/himin/menu/api/MenuOptionGroupControllerTest.java, src/test/java/com/prgrms/himin/menu/docs/MenuDocumentationTest.java, src/test/java/com/prgrms/himin/menu/docs/MenuOptionDocumentationTest.java, src/test/java/com/prgrms/himin/menu/docs/MenuOptionGroupDocumentationTest.java, src/test/java/com/prgrms/himin/setup/response/MenuCreateResponseBuilder.java, src/test/java/com/prgrms/himin/setup/response/MenuOptionCreateResponseBuilder.java, src/test/java/com/prgrms/himin/setup/response/MenuOptionGroupCreateResponseBuilder.java, src/test/java/com/prgrms/himin/setup/response/MenuResponseBuilder.java
- 테스트를 위한 response 기능 추가 
- 메뉴, 메뉴 옵션 그룹, 메뉴 옵션 API restdocs 추가 
- 기존 테스트 버그 수정
- 기존 테스트에서 사용하지 않은 메서드 제거
Issue Number: HIMIN-228
=> [HIMIN-228] test : 메뉴, 메뉴 옵션 그룹, 메뉴 옵션 API restdocs 추가

src/main/java/com/prgrms/himin/global/config/security/WebSecurityConfig.java, src/main/java/com/prgrms/himin/global/config/security/jwt/JwtAuthenticationFilter.java, src/main/java/com/prgrms/himin/global/config/security/jwt/JwtAuthenticationProvider.java, src/main/java/com/prgrms/himin/member/api/MemberController.java, src/main/java/com/prgrms/himin/member/application/MemberService.java, src/main/java/com/prgrms/himin/member/domain/Member.java, src/test/java/com/prgrms/himin/member/api/MemberControllerTest.java, src/test/java/com/prgrms/himin/member/application/MemberServiceTest.java, src/test/java/com/prgrms/himin/member/docs/MemberDocumentationTest.java, src/test/java/com/prgrms/himin/setup/response/MemberLoginResponseBuilder.java
Issue Number: NO-ZIRA, HIMIN-229
=> [NO-ZIRA] refactor: JWT를 이용한 로그인 로직 이동 & [HIMIN-229] test: 로그인 테스트 추가

src/docs/delivery.adoc, src/docs/menu.adoc, src/test/java/com/prgrms/himin/delivery/docs/DeliveryDocumentationTest.java, src/test/java/com/prgrms/himin/menu/api/MenuControllerTest.java, src/test/java/com/prgrms/himin/menu/docs/MenuDocumentationTest.java
=> [HIMIN-229] test : adoc 작성

src/docs/member.adoc, src/docs/order.adoc, src/test/java/com/prgrms/himin/order/docs/OrderDocumentationTest.java
- 회원, 주문 도메인 adoc 추가
Issue Number: HIMIN-229
=> [HIMIN-229] docs: 회원, 주문 도메인 adoc 추가

src/docs/menu.adoc, src/docs/menuOption.adoc, src/docs/menuOptionGroup.adoc, src/docs/shop.adoc, src/test/java/com/prgrms/himin/shop/docs/ShopDocumentationTest.java
=> [HIMIN-229] 메뉴,가게 adoc 작성

BOOT-INF/classes/static/docs/delivery.html, BOOT-INF/classes/static/docs/index.html, BOOT-INF/classes/static/docs/member.html, BOOT-INF/classes/static/docs/menu.html, BOOT-INF/classes/static/docs/menuOption.html, BOOT-INF/classes/static/docs/menuOptionGroup.html, BOOT-INF/classes/static/docs/order.html, BOOT-INF/classes/static/docs/shop.html, build.gradle, src/docs/asciidoc/delivery.adoc, src/docs/asciidoc/index.adoc, src/docs/asciidoc/member.adoc, src/docs/asciidoc/menu.adoc, src/docs/asciidoc/menuOption.adoc, src/docs/asciidoc/menuOptionGroup.adoc, src/docs/asciidoc/order.adoc, src/docs/asciidoc/shop.adoc, src/main/resources/static/docs/delivery.html, src/main/resources/static/docs/index.html, src/main/resources/static/docs/member.html, src/main/resources/static/docs/menu.html, src/main/resources/static/docs/menuOption.html, src/main/resources/static/docs/menuOptionGroup.html, src/main/resources/static/docs/order.html, src/main/resources/static/docs/shop.html
restdocs 생성
Issue Number: HIMIN-229
=> [HIMIN-229] feat : restdocs html 생성
